//! Static-site renderer: turns doc IR plus module maps into a
//! self-contained HTML tree (no server, no external requests).
//!
//! The site is a set of language *trees* (`cpp/`, `c/`, `py/`), each with
//! its own module hierarchy and pages, sharing one search index and one
//! landing page. All Markdown and signature text is pre-rendered in Rust
//! into view models; the embedded minijinja templates only do layout.

mod guide;
pub(crate) mod highlight;
mod md;
mod pages;
pub mod rst;
mod sig;
mod views;

pub use guide::{GuideInput, collect_sig_directives, scan_rst_warnings};

use std::collections::HashMap;
use std::path::Path;

use crate::ir::{Item, Module};
use crate::link::Family;
use anyhow::{Context, Result};
use minijinja::{Environment, context};
use serde::Serialize;

use crate::render::md::Resolver;

/// One language tree of the site.
pub struct TreeInput<'a> {
    /// Display title, e.g. "C++ API".
    pub title: &'a str,
    /// URL prefix, e.g. "cpp" — pages land under `<prefix>/...`.
    pub prefix: &'a str,
    /// Root namespace stripped from display names and URLs (e.g. `Botan`,
    /// so `Botan::TLS::Policy` renders as `TLS::Policy`).
    pub root_namespace: Option<&'a str>,
    /// Include-form prefix for "Defined in" display (`botan` renders
    /// <botan/header.h>); None shows the bare basename.
    pub include_prefix: Option<&'a str>,
    pub modules: &'a [Module],
    pub items: &'a [Item],
}

pub struct RenderInput<'a> {
    /// Presence-only names for xref resolution (external headers,
    /// macros) — build-side role warnings must judge like the check.
    pub reference_names: &'a [String],
    pub project: &'a str,
    pub trees: Vec<TreeInput<'a>>,
    /// Class <-> C-function-family edges from the binding map.
    pub families: &'a [Family],
    /// Markdown prose pages, rendered with API autolinks.
    pub guide: Option<GuideInput<'a>>,
    pub branding: Branding<'a>,
}

/// The supported theming surface. Files are copied into `static/`.
#[derive(Default)]
pub struct Branding<'a> {
    pub extra_css: Option<&'a Path>,
    pub logo: Option<&'a Path>,
    pub favicon: Option<&'a Path>,
    pub footer: Option<&'a str>,
}

#[derive(Serialize, Default)]
struct BrandingView {
    extra_css: Option<String>,
    logo: Option<String>,
    favicon: Option<String>,
    footer: Option<String>,
}

/// Marks a directory as udg-generated (and therefore safe to replace).
const SITE_MARKER: &str = ".udg-site";

pub struct RenderOutput {
    pub pages_written: usize,
    pub search_entries: usize,
    pub warnings: Vec<String>,
}

#[derive(Serialize)]
struct LandingTree {
    title: String,
    prefix: String,
    stats: String,
    tree_html: String,
}

pub fn render(input: &RenderInput, final_dir: &Path) -> Result<RenderOutput> {
    // Never delete a directory udg did not create: a previous site
    // carries the `.udg-site` marker; anything else non-empty is
    // refused rather than replaced.
    if final_dir.exists()
        && !final_dir.join(SITE_MARKER).exists()
        && std::fs::read_dir(final_dir)
            .with_context(|| format!("cannot read {}", final_dir.display()))?
            .next()
            .is_some()
    {
        anyhow::bail!(
            "output directory {} exists and was not created by udg (no {SITE_MARKER} marker); \
             refusing to replace it — point [output] dir at a new or empty directory",
            final_dir.display()
        );
    }
    // Render into a staging sibling and swap only on success: a failed
    // build must leave the previous site intact.
    let name = final_dir
        .file_name()
        .and_then(|n| n.to_str())
        .ok_or_else(|| anyhow::anyhow!("output dir must be a named directory"))?;
    let parent = final_dir.parent().unwrap_or_else(|| Path::new("."));
    std::fs::create_dir_all(parent)?;
    let staging = parent.join(format!(".{name}.udg-staging"));
    if staging.exists() {
        // Leftover from an interrupted build; ours by construction.
        std::fs::remove_dir_all(&staging)
            .with_context(|| format!("cannot clean stale staging dir {}", staging.display()))?;
    }
    std::fs::create_dir_all(&staging)?;
    std::fs::write(
        staging.join(SITE_MARKER),
        "generated by udg; this directory is deleted on rebuild\n",
    )?;
    // Everything below renders into the staging directory.
    let out_dir: &Path = &staging;

    let mut env = Environment::new();
    for (name, src) in [
        ("base.html", include_str!("templates/base.html")),
        ("landing.html", include_str!("templates/landing.html")),
        ("index.html", include_str!("templates/index.html")),
        ("module.html", include_str!("templates/module.html")),
        ("record.html", include_str!("templates/record.html")),
        ("enum.html", include_str!("templates/enum.html")),
        ("leaf.html", include_str!("templates/leaf.html")),
        ("source.html", include_str!("templates/source.html")),
        ("guide.html", include_str!("templates/guide.html")),
        ("embed.html", include_str!("templates/embed.html")),
        ("docblock.html", include_str!("templates/docblock.html")),
    ] {
        env.add_template(name, src)
            .with_context(|| format!("bad template {name}"))?;
    }

    // Branding assets: copied into static/, exposed to every template
    // via a global.
    let static_dir = out_dir.join("static");
    std::fs::create_dir_all(&static_dir)?;
    let copy_asset = |src: &Path, base: &str| -> Result<String> {
        let ext = src.extension().and_then(|e| e.to_str()).unwrap_or("bin");
        let name = format!("{base}.{ext}");
        std::fs::copy(src, static_dir.join(&name))
            .with_context(|| format!("cannot copy branding asset {}", src.display()))?;
        Ok(name)
    };
    let branding_view = BrandingView {
        extra_css: input
            .branding
            .extra_css
            .map(|p| copy_asset(p, "extra"))
            .transpose()?,
        logo: input
            .branding
            .logo
            .map(|p| copy_asset(p, "logo"))
            .transpose()?,
        favicon: input
            .branding
            .favicon
            .map(|p| copy_asset(p, "favicon"))
            .transpose()?,
        footer: input.branding.footer.map(str::to_owned),
    };
    env.add_global("branding", minijinja::Value::from_serialize(&branding_view));

    let mut others: Vec<(String, String)> = input
        .trees
        .iter()
        .map(|t| (t.title.to_owned(), t.prefix.to_owned()))
        .collect();
    if let Some(g) = &input.guide {
        others.push((g.title.to_owned(), "guide".to_owned()));
    }

    // Two phases: plan every tree first so cross-tree links (bindings,
    // autolinks into other languages) can resolve, then render.
    let sites: Vec<pages::Site> = input
        .trees
        .iter()
        .map(|tree| pages::Site::build(input.project, tree, &others))
        .collect();
    let mut id_url = HashMap::new();
    for site in &sites {
        id_url.extend(site.plan_urls());
    }
    let mut symbols =
        crate::link::SymbolIndex::build(input.trees.iter().map(|t| (t.items, t.root_namespace)));
    symbols.add_presence(input.reference_names.iter().cloned());
    let symbols = symbols;
    // Reverse inheritance: resolve every class's bases and invert.
    let mut derived: HashMap<String, Vec<pages::DerivedEntry>> = HashMap::new();
    for tree in &input.trees {
        for top in tree.items {
            top.walk(&mut |i| {
                use crate::ir::ItemKind;
                if !matches!(i.kind, ItemKind::Class | ItemKind::Struct) {
                    return;
                }
                for base in &i.bases {
                    let name = base.split('<').next().unwrap_or(base).trim();
                    if let crate::link::Resolution::Unique(base_id) =
                        symbols.resolve(name, None, Some(i.lang))
                    {
                        let display = match tree.root_namespace {
                            Some(ns) => i
                                .qualified_name
                                .strip_prefix(ns)
                                .and_then(|r| r.strip_prefix("::"))
                                .unwrap_or(&i.qualified_name),
                            None => &i.qualified_name,
                        };
                        derived
                            .entry(base_id)
                            .or_default()
                            .push(pages::DerivedEntry {
                                display: display.to_owned(),
                                id: i.id.clone(),
                                summary: i.docs.as_ref().and_then(|d| d.summary.clone()),
                            });
                    }
                }
            });
        }
    }
    for v in derived.values_mut() {
        v.sort_by(|a, b| a.display.cmp(&b.display));
        v.dedup_by(|a, b| a.id == b.id);
    }

    let mut items_by_id: HashMap<String, &Item> = HashMap::new();
    fn index_items<'a>(item: &'a Item, map: &mut HashMap<String, &'a Item>) {
        map.entry(item.id.clone()).or_insert(item);
        for c in &item.children {
            index_items(c, map);
        }
    }
    for tree in &input.trees {
        for item in tree.items {
            index_items(item, &mut items_by_id);
        }
    }

    let link = pages::LinkCtx {
        symbols: &symbols,
        id_url: &id_url,
        families: input.families,
        derived: &derived,
        items_by_id: &items_by_id,
    };

    let mut search = Vec::new();
    let mut pages_written = 0usize;
    let mut warnings = Vec::new();
    let mut landing_trees = Vec::new();

    for (tree, site) in input.trees.iter().zip(&sites) {
        pages_written += site.write(&env, out_dir, &mut search, &link)?;
        warnings.extend(site.warnings().to_vec());
        landing_trees.push(LandingTree {
            title: tree.title.to_owned(),
            prefix: tree.prefix.to_owned(),
            stats: site.stats_line(),
            tree_html: site.module_tree_html(""),
        });
    }

    if let Some(g) = &input.guide {
        let out = guide::write_guides(
            &env,
            out_dir,
            g,
            input.project,
            &others,
            &symbols,
            &id_url,
            &items_by_id,
            &mut search,
        )?;
        pages_written += out.pages_written;
        warnings.extend(out.warnings.iter().cloned());
        landing_trees.push(LandingTree {
            title: g.title.to_owned(),
            prefix: "guide".to_owned(),
            stats: format!("{} pages", out.pages_written.saturating_sub(1)),
            tree_html: out.list_html,
        });
    }

    let landing_nav: String = {
        let mut out = String::from("<div class=\"navtitle\">APIs</div><ul class=\"navtree\">");
        for (title, prefix) in &others {
            out.push_str(&format!(
                "<li><a href=\"{prefix}/index.html\">{}</a></li>",
                html_escape(title)
            ));
        }
        out.push_str("</ul>");
        out
    };
    let landing = env.get_template("landing.html")?.render(context! {
        project => input.project,
        title => format!("{} documentation", input.project),
        root => "",
        nav_html => landing_nav,
        crumbs => Vec::<views::Crumb>::new(),
        trees => landing_trees,
    })?;
    std::fs::create_dir_all(out_dir)?;
    std::fs::write(out_dir.join("index.html"), landing)?;
    pages_written += 1;

    // The index is a script that assigns a global, not fetched JSON:
    // fetch() is CORS-blocked on file:// URLs, and docs must work when
    // opened straight from disk. search.js lazily injects this script.
    let search_entries = search.len();
    std::fs::write(
        out_dir.join("search-index.js"),
        format!(
            "window.UDG_SEARCH_INDEX = {};\n",
            serde_json::to_string(&search)?
        ),
    )?;

    std::fs::write(
        static_dir.join("style.css"),
        include_str!("static/style.css"),
    )?;
    std::fs::write(
        static_dir.join("search.js"),
        include_str!("static/search.js"),
    )?;

    // Success: replace the previous site (validated above as ours or
    // empty) with the staged one.
    if final_dir.exists() {
        std::fs::remove_dir_all(final_dir)
            .with_context(|| format!("cannot replace {}", final_dir.display()))?;
    }
    std::fs::rename(&staging, final_dir).with_context(|| {
        format!(
            "cannot move staged site {} into place at {}",
            staging.display(),
            final_dir.display()
        )
    })?;

    Ok(RenderOutput {
        pages_written,
        search_entries,
        warnings,
    })
}

/// `../` prefix that leads from a site-root-relative URL back to the root.
fn root_prefix(url: &str) -> String {
    "../".repeat(url.matches('/').count())
}

/// Make a name safe for a file path component; keeps letters, digits,
/// `_ . -`, encodes everything else as `_XX` hex (stable, collision-free
/// enough for identifier-ish inputs like `operator==`).
fn sanitize(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for c in name.chars() {
        if c.is_ascii_alphanumeric() || matches!(c, '_' | '.' | '-') {
            out.push(c);
        } else {
            for b in c.to_string().as_bytes() {
                out.push_str(&format!("_{b:02X}"));
            }
        }
    }
    out
}

/// HTML-escape signature text, wrapping identifier paths that resolve
/// to API items in links (`RandomNumberGenerator & rng` links the type).
/// Escaping and linking happen in one pass over the raw text so entity
/// names (&amp;) can never be mistaken for identifiers.
/// Render signature chunks: type positions autolink, everything else
/// is only escaped.
pub(crate) fn linkify_chunks(chunks: &[sig::Chunk], res: Option<Resolver>) -> String {
    chunks
        .iter()
        .map(|c| {
            if c.ty {
                linkify_sig(&c.text, res)
            } else {
                html_escape(&c.text)
            }
        })
        .collect()
}

pub(crate) fn linkify_sig(text: &str, res: Option<Resolver>) -> String {
    let chars: Vec<char> = text.chars().collect();
    let mut out = String::with_capacity(text.len());
    let mut i = 0;
    while i < chars.len() {
        let c = chars[i];
        if c.is_ascii_alphabetic() || c == '_' {
            let start = i;
            let mut j = i;
            loop {
                while j < chars.len() && (chars[j].is_ascii_alphanumeric() || chars[j] == '_') {
                    j += 1;
                }
                if j + 2 < chars.len()
                    && chars[j] == ':'
                    && chars[j + 1] == ':'
                    && (chars[j + 2].is_ascii_alphabetic() || chars[j + 2] == '_')
                {
                    j += 2;
                } else {
                    break;
                }
            }
            let token: String = chars[start..j].iter().collect();
            match res.and_then(|r| r(&token)) {
                Some(href) => {
                    out.push_str(&format!("<a href=\"{href}\">{}</a>", html_escape(&token)));
                }
                None => out.push_str(&html_escape(&token)),
            }
            i = j;
        } else {
            match c {
                '&' => out.push_str("&amp;"),
                '<' => out.push_str("&lt;"),
                '>' => out.push_str("&gt;"),
                '"' => out.push_str("&quot;"),
                _ => out.push(c),
            }
            i += 1;
        }
    }
    out
}

fn html_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            _ => out.push(c),
        }
    }
    out
}
